### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by xiaadmin** [yi-ge/node-pdf-printer#11]
UnhandledPromiseRejectionWarning: Error: Command failed: %WINdir%\System32\cscript.exe %WINdir%\System32\printing_Admin_Scripts\en-US\prnmngr.vbs -l | find /i "Printer name"

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
(node:5292) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5292) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by yi-ge** [comment]
Check your path `%WINdir%\System32\printing_Admin_Scripts\en-US`?
