### ISSUE TITLE
Rapidly printing files prints last file submitted multiple times instead of individual files

### ISSUE THREAD

**Issue by epelc** [yi-ge/node-pdf-printer#12]
Hello,

Just noticed that if you print multiple files without much delay between them then it will not print each unique file but will instead print multiple copies of the last file submitted.

I believe this is due to using a single global filename for the `printTmp.bat` as it is getting overridden with each call.

https://github.com/yi-ge/node-pdf-printer/blob/master/src/index.js#L33

**Comment by epelc** [comment]
Will submit a patch soon.

Can use `npm i --save @greatcloak/node-pdf-printer` for latest fix in mean time.

**Comment by yi-ge** [comment]
Cool~
