### ISSUE TITLE
Print settings

### ISSUE THREAD

**Issue by Vasenti** [yi-ge/node-pdf-printer#3]
It always prints to me horizontally, is there any way to change these settings, such as putting it vertically, print size or something?

**Comment by yi-ge** [comment]
Yes, use  `.dat` file.

Whether or not you specify a printer, you can specify a page range to print by adding an optional parameter, like this:

PDFtoPrinter filename.pdf pages=#-#

Separate multiple page ranges with commas (no spaces) like this: 2-4,7,12 or, to specify all pages after a specific page, use its number followed by a hyphen, like this: 7-

 Customization: By default, this system uses these printing options as set in PDF-XChange Viewer: Scaling is set to None; Auto-rotate Sheets; Auto-centre pages in sheets; and Choose paper source by PDF-page size. If you want to change any of these, or choose any other options, download and install PDF-XChange Viewer; open a PDF file, go to the Print menu, set your desired options (and, just to be certain, print the file). Then go to the Edit menu and choose Export All Settings to Data File... Accept the suggested filename, "PDF-XChange Viewer Settings.dat", and save the file to a convenient location. Move or copy the file to the same folder with PDFtoPrinter.exe. When you next run PDFtoPrinter.exe it will use the settings saved in that file.

Duplex printing: PDF-XChange Viewer cannot save a duplex-printing option as the default. To print in duplex mode, modify the settings of your Windows printer (in the Windows Control Panel or Settings app) to enable duplex printing, or create a duplicate copy of your Windows printer, set it to print in duplex by default, and specify that printer when running PDFtoPrinter.exe. Search the web if you don't know how to create a duplicate copy of your Windows printer or if you don't know how to specify duplex printing in your Windows printer properties.

More: http://www.columbia.edu/~em36/pdftoprinter.html

**Comment by Vasenti** [comment]
I have used the ".dat" configuration file from PDF-XChange Viewer. But keep printing horizontally, when what I want is to do it vertically. I already tried to print it only with PDF-XChange Viewer without PDFtoPrinter.exe and it worked as I wanted.

**Comment by Vasenti** [comment]
I have found the problem. What happens is that I must put directly in the printing preferences in windows directly, not through PDF-XChange Viewer, because it does not save the configuration in windows.

**Comment by yi-ge** [comment]
Yes, using the system default settings will solve this problem. If possible, I will rewrite a print library using golang.
